#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn check-format ||
(
    echo '🤢🤮 Prettier Check Failed. Run yarn format, add changes and try commit again.';
    yarn format
)

# Check ESLint Standards
yarn check-lint ||
(
        echo '😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
yarn check-types ||
(
    echo '🤡❌ Failed Type check. Make the changes required above.'
    false;
)

# echo "No errors yet... Let's test it out!"

# yarn test ||
# (
#     echo '❌ Failed tests. Make the changes required above.'
#     false;
# )

# If everything passes... Now we can commit
echo '🤔 Alright... The code looks good to me, trying to build now.'

# yarn build ||
# (
#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#             Next build failed: View the errors above to see why. 
#     '
#     false;
# )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
